CREATE TABLE IF NOT EXISTS navbar (
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT NOT NULL,
url TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS posts (
id INTEGER PRIMARY KEY AUTOINCREMENT,
title TEXT NOT NULL,
category TEXT NOT NULL,
text TEXT NOT NULL,
image BLOB NOT NULL,
url TEXT NOT NULL,
time TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS comments (
id INTEGER PRIMARY KEY AUTOINCREMENT,
text TEXT NOT NULL,
url TEXT NOT NULL,
time TEXT NOT NULL
);