CREATE TABLE IF NOT EXISTS navbar (
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT NOT NULL,
url TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS posts (
id INTEGER PRIMARY KEY AUTOINCREMENT,
title TEXT NOT NULL,
category TEXT NOT NULL,
text TEXT NOT NULL,
image BLOB NOT NULL,
url TEXT NOT NULL,
time TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
id INTEGER PRIMARY KEY AUTOINCREMENT,
username TEXT NOT NULL,
email TEXT NOT NULL,
password TEXT NOT NULL,
time TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS comments (
id INTEGER PRIMARY KEY AUTOINCREMENT,
text TEXT NOT NULL,
url TEXT NOT NULL,
time TEXT NOT NULL,
user_id INTEGER REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS feedback (
id      INTEGER PRIMARY KEY AUTOINCREMENT,
name    TEXT    NOT NULL,
email   TEXT    NOT NULL,
message TEXT    NOT NULL,
time    TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS subscription (
id      INTEGER PRIMARY KEY AUTOINCREMENT,
email   TEXT    NOT NULL,
time    TEXT    NOT NULL
);