# Generated by Django 4.2.4 on 2023-08-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_app', '0005_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ws_app/%Y/%m/%d'),
        ),
    ]
