# Generated by Django 4.2.4 on 2023-09-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_app', '0014_alter_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='characteristics',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
