# Generated by Django 4.2.4 on 2023-09-05 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ws_app', '0016_alter_product_characteristics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='characteristics',
        ),
    ]
