# Generated by Django 4.2.4 on 2023-09-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_app', '0020_remove_product_test_product_characteristics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ratio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('categories', models.ManyToManyField(blank=True, to='ws_app.category')),
                ('manufacturers', models.ManyToManyField(blank=True, to='ws_app.manufacturer')),
                ('products', models.ManyToManyField(blank=True, to='ws_app.product')),
            ],
        ),
    ]
