# Generated by Django 4.2.4 on 2023-08-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_items_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
