# Generated by Django 4.2.4 on 2023-09-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_app', '0015_product_characteristics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='characteristics',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
