# Generated by Django 4.2.4 on 2023-09-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_app', '0018_product_characteristics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='characteristics',
        ),
        migrations.AddField(
            model_name='product',
            name='test',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
