# Generated by Django 3.1.14 on 2023-08-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbaritem',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
